#' Get the path of the current R or Quarto script
#'
#' Attempts to determine the file path of the active R or Quarto source file.
#' This covers execution via `Rscript`, sourcing in the console,
#' interactive editing in RStudio/Positron, and Quarto/R Markdown rendering.
#'
#' @details
#' The detection order is:
#' \enumerate{
#'   \item Command line execution (via `Rscript myscript.R`);
#'   \item Manual sourcing (`source("file.R")`);
#'   \item Interactive editing in RStudio/Positron;
#'   \item Quarto or R Markdown rendering (`knitr::current_input()` or `rmarkdown::metadata()`).
#' }
#'
#' In Quarto documents, the function returns the path of the
#' `.qmd` file being rendered, not the intermediate `.R` script
#' generated by `knitr`.
#'
#' @return A normalized file path (character string).
#' If no valid path can be determined, the function errors.
#'
#' @examples
#' \dontrun{
#' # Typical use
#' path <- get_script_path()
#' fs::path_dir(path)
#' }
#'
#' @export
get_script_path <- function() {
  # 1. Command line (e.g., Rscript myfile.R)
  args_all <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args_all, value = TRUE)
  if (length(file_arg)) {
    return(normalizePath(sub("^--file=", "", file_arg), winslash = "/"))
  }

  # 2. Sourced manually
  if (!is.null(sys.frame(1)$ofile)) {
    return(normalizePath(sys.frame(1)$ofile, winslash = "/"))
  }

  # 3. Inside RStudio / Positron
  if (
    requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()
  ) {
    p <- tryCatch(
      rstudioapi::getActiveDocumentContext()$path,
      error = function(e) ""
    )
    if (nzchar(p)) return(normalizePath(p, winslash = "/"))
  }

  # 4. When knitting or rendering Quarto / R Markdown
  # knitr provides `current_input()` inside chunks
  if (
    requireNamespace("knitr", quietly = TRUE) &&
      !is.null(knitr::current_input())
  ) {
    p <- knitr::current_input()
    if (nzchar(p)) return(normalizePath(p, winslash = "/"))
  }

  # Quarto executes under rmarkdown::metadata() when knitting
  if (requireNamespace("rmarkdown", quietly = TRUE)) {
    p <- tryCatch(rmarkdown::metadata$output_file, error = function(e) "")
    if (nzchar(p)) return(normalizePath(p, winslash = "/"))
  }

  stop("Cannot determine script path in the current session.")
}
