#' Write a YAML sidecar file containing metadata
#'
#' Creates or overwrites a `.meta.yml` (or other specified) sidecar file
#' containing key–value metadata pairs. This function is used internally
#' when inline comment injection is not supported by the target file type
#' (e.g., binary outputs such as `.pdf` or `.png`).
#'
#' @param sidecar_path Character string giving the output path for the YAML
#'   sidecar file. Typically generated by
#'   \code{fs::path_ext_set(original_path, "meta.yml")}.
#' @param metadata Named list of scalar or vector elements representing metadata
#'   fields (e.g., as returned by \code{\link{collect_output_metadata}()}).
#'
#' @details
#' The function flattens the input list to single-line character values.
#' If the \pkg{yaml} package is available, the metadata are serialized using
#' \code{yaml::as.yaml()} with two-space indentation.
#' If \pkg{yaml} is not installed, the function falls back to writing a simple
#' line-based key–value text file of the form:
#'
#' ```
#' key: value
#' another_key: another value
#' ```
#'
#' Each field is coerced to character; multi-element values are collapsed with
#' commas.
#'
#' @return
#' Invisibly returns \code{NULL}. Called for its side effect of writing the
#' sidecar file.
#'
#' @examples
#' \dontrun{
#' meta <- list(
#'   project_root = "/Users/asle/GPFG",
#'   script_path = "R/analysis/fig_returns.R",
#'   git_commit = "a8c42f1"
#' )
#'
#' .write_yaml_sidecar("figures/fig_returns.meta.yml", meta)
#' }
#'
#' @seealso [write_metadata_block()] for higher-level metadata writing that
#' calls this helper when inline injection is not supported.
#'
#' @keywords internal
#' @noRd

.write_yaml_sidecar <- function(sidecar_path, metadata) {
  # Flatten to character scalars
  stopifnot(is.list(metadata))
  meta_chr <- lapply(metadata, function(x) {
    if (length(x) <= 1) as.character(x) else paste(x, collapse = ", ")
  })
  # Prefer yaml if available; else write a simple key: value file
  if (requireNamespace("yaml", quietly = TRUE)) {
    txt <- yaml::as.yaml(
      meta_chr,
      indent = 2,
      line.sep = "\n",
      handlers = list()
    )
    writeLines(txt, sidecar_path, useBytes = TRUE)
  } else {
    lines <- sprintf(
      "%s: %s",
      names(meta_chr),
      vapply(meta_chr, function(x) x %||% "", character(1))
    )
    writeLines(lines, sidecar_path, useBytes = TRUE)
  }
}
